# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: 47.254.243.60
          username: root
          password: CXbTu47mlG
          port: 22
          script: 
            cd ../var/www/
      - name: remove existed directory
        run: sudo rm simple_crud
      - name: execute git pull
        run: git clone https://github.com/saputroandi/simple-crud
      - name: check status
        run: git status
      - name: composer install
        run: composer install
      - name: answer yes
        run: yes
      - name: restart ngincx
        run: sudo systemctl restart nginx
